### ISSUE TITLE
docs(global): 📝 License badge in README.md not showing properly

### ISSUE THREAD

**Issue by rahulkarda** [100Devs-ADHD/think-big#5]
# Bug Report

**ThinkBIG version:**

**Current behavior:**  License Badge shows 'not identifiable by github'

**Expected behavior:** License Badge should show GPLv3

**Steps to reproduce:** View repo README

**Related code:** README.md

**Other information:**

**Comment by GarlandKey** [comment]
More research and discussion is necessary with the core team before we can specify which license the project will adopt. Thank you for suggestion. I will bring this up in our next team meeting.

**Comment by GarlandKey** [comment]
This issue has been resolved. @[rahulkarda](https://github.com/rahulkarda) Thanks so much for contributing!

**Comment by rahulkarda** [comment]
Thanks!
