### ISSUE TITLE
dev: UI: Update HeaderBar

### ISSUE THREAD

**Issue by GarlandKey** [100Devs-ADHD/think-big#77]
## Prototype

<div align="center">

<img src="https://raw.githubusercontent.com/100Devs-ADHD/assets/main/thinkbig/issues/HeaderBar.webp" title="prototype example">

_Note: The search bar is not part of the mvp and will be implemented later._

Logo location: `/thinkbig-logo.svg`

</div>

## Styling

**Element**

Logo:

```css
  height: 60px;
  width: 236px;
```

**Comment by JoeKarow** [comment]
Please save the svg file in the /public/ folder.

**Comment by JoeKarow** [comment]
The search bar is already in there as a placeholder - for the time being, we can just comment out these lines in the code:
https://github.com/100Devs-ADHD/think-big/blob/9e365d1f8f7ab6a111b2c5b8102f718abf598e4b/src/components/HeaderBar.tsx#L37-L44
