### ISSUE TITLE
feat: UI: Tags 

### ISSUE THREAD

**Issue by vampyteuth** [100Devs-ADHD/think-big#78]
## Feature Description
Create tags that are color-specific and labeled.
Labels to include (there are many more I am sure):

| **Frontend**  | **Backend**   | **Events**    | **Tools**     |
| ------------- | ------------- | ------------- | ------------- |
| Async/Await   | API           | Anki          | Bash          |
| CRUD          | Backend       | Assignment    | Git           |           
| CSS           | Express       | Banki         | GitHub        |
| Flexbox       | MongoDB       | Class         | Heroku        |
| Floats        | Node          | Freelance     | Netlify       |             
| Frontend      |               | Networking    | Postman       |
| HTML          |               | The Hunt      |               |
| JavaScript    |               | Spicy Rant    |               |
| OOP           |               | Motivational  |               |
| React         |               |               |               |
| ShayHowe      |               |               |               |

**Describe the Feature Request**
Tags can be clicked to link to other pages that discuss tag topic. Tags are searchable and should be highly visible and easy to access.

## Definition of Done

- [x] Component is self-closing & takes an array of tag names as a prop and displays the appropriate group of tags. Example:
  ```jsx
	<TagGroup tags={[{name: 'Git', color: '#000000'}, {name: 'Spicy Rant', color: '#ffffff'}, {name: 'CSS', color: '#666666'}]} />
	```
- [x] Tags are color specific
- [x] As a placeholder until the database is fully up and running, create a separate js file in `/mockdata/` with the tag name & associated color in the following format: 
  ```js
	export const tagData = [
		{ name: '*tag-name*',
		  color: '#*hexcode*'
		}, ...
	```
- [x] Tag name and associated color render.

## Prototype
<img width="550" alt="image" src="https://user-images.githubusercontent.com/94151404/180332827-b233f49b-afc8-4354-9308-6c7667cf04a0.png">

## Styling & Components
- Tag use: https://mantine.dev/core/chips/
- Class detail Modal #76 

## Comments/Questions
These are not UI components but important to think about:
- How will new tags be entered? `mock data js file for now, database later`
- Is there an option for users to add new tags? `could get really messy`
- Can tags be auto-generated from the class title? `best to just include the tag list as part of the class data object`
- Tags are searchable 

### Other Helpful Info

- Enclose the individual tags in a `<Chips> </Chips>` tag.
- Use a map() method on the `tags` array that is received via `props`

**Comment by vampyteuth** [comment]
Need to edit the labels and add to the Projects and Milestone but it is grayed out for me?!?!

**Comment by GarlandKey** [comment]
Edited the list of labels to be in a table to take up less space and be more verbose.

**Comment by JoeKarow** [comment]
@vampyteuth @jcvdg We'll tackle this during our Wednesday session.
